version: '3.9'

services:
  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SERVICE_TYPE: api
      DATABASE_PATH: ${DATABASE_PATH:-/app/data/apiflow.db}
      ADMIN_LOGIN: ${ADMIN_LOGIN:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    restart: unless-stopped

  # Worker Service
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_TYPE: worker
      DATABASE_PATH: ${DATABASE_PATH:-/app/data/apiflow.db}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped

  # SQLite Viewer
  sqlite-viewer:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    command: ["sqlite_web", "-H", "0.0.0.0", "-x", "/data/apiflow.db"]
    depends_on:
      - api
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: ${PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
